name: Build Resume

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Build and run Docker container
        run: |
          # Создаем структуру директорий
          mkdir -p resume
          cp CV/* resume/ || true  # Копируем файлы резюме
          cp altacv.cls resume/ || true
          
          # Создаем Dockerfile
          cat << EOF > Dockerfile
          FROM fedora:32  # Используем Fedora 32 напрямую

          # Установка пакетов
          RUN dnf install -y \\
              texlive-collection-latexrecommended \\
              texlive-collection-fontsrecommended \\
              texlive-collection-pictures \\
              texlive-collection-science \\
              texlive-collection-langcyrillic \\
              texlive-collection-latexextra \\
              texlive-collection-fontsextra \\
              texlive-wallpaper \\
              texlive-geometry \\
              texlive-fontawesome5 \\
              texlive-hyperref \\
              texlive-hyphenat \\
              texlive-graphics \\
              texlive-tools \\
              texlive-luatex \\
              texlive-luatex85 \\
              texlive-cm-super \\
              texlive-ctablestack \\
              texlive-luatexbase \\
              make \\
              git \\
              wget \\
              unzip \\
              python3 \\
              dejavu-sans-fonts \\
              google-noto-sans-fonts \\
              liberation-fonts \\
              && dnf clean all

          # Рабочая директория
          WORKDIR /app
          
          # Копирование файлов
          COPY resume/build.sh .
          COPY resume/choose_system.py .
          COPY resume/resume.tex .
          COPY resume/altacv.cls .
          
          # Права на выполнение
          RUN chmod 755 build.sh
          
          # Команда запуска
          CMD ["./build.sh"]
          EOF
          
          # Сборка и запуск контейнера
          docker build -t resume-builder .
          docker run --rm -v $(pwd)/output:/app/output resume-builder

      - name: Verify PDF exists
        run: |
          if [ ! -f output/resume.pdf ]; then
            echo "PDF file not generated!"
            ls -la output
            exit 1
          else
            echo "PDF generated successfully"
            mv output/resume.pdf .
            ls -lh resume.pdf
          fi

      - name: Prepare GitHub Pages
        run: |
          mkdir -p public/cv
          cp resume.pdf public/cv/
          
          # Создаем редирект
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8">
              <title>Resume - Ксения Шкулева</title>
              <meta http-equiv="refresh" content="0; url=cv/resume.pdf">
              <script>window.location.href="cv/resume.pdf";</script>
            </head>
            <body>
              <p>Redirecting to <a href="cv/resume.pdf">resume.pdf</a></p>
            </body>
          </html>' > public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          commit_message: "Auto-update: $(date -u +'%Y-%m-%d %H:%M')"
