name: Build Resume

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Fedora 32 Environment
        run: |
          # Создаем Dockerfile
          cat << EOF > Dockerfile
          FROM fedora:31

          RUN dnf upgrade -y --releasever=32 && \\
              dnf update -y && \\
              dnf install -y \\
                  texlive-collection-latexrecommended \\
                  texlive-collection-fontsrecommended \\
                  texlive-collection-pictures \\
                  texlive-collection-science \\
                  texlive-collection-langcyrillic \\
                  texlive-collection-latexextra \\
                  texlive-collection-fontsextra \\
                  texlive-wallpaper \\
                  texlive-geometry \\
                  texlive-fontawesome5 \\
                  texlive-hyperref \\
                  texlive-hyphenat \\
                  texlive-graphics \\
                  texlive-tools \\
                  make \\
                  git \\
                  wget \\
                  unzip \\
                  python3 \\
                  texlive-lm \\
                  texlive-psnfss \\
                  texlive-helvetic \\
                  texlive-carlito \\
                  texlive-fira \\
              && dnf clean all

          RUN wget -q https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Arial.zip && \\
              unzip -q Arial.zip -d /usr/share/fonts/ && \\
              fc-cache -fv && \\
              rm Arial.zip

          WORKDIR /app
          COPY . .
          RUN chmod 755 build.sh
          CMD ["./build.sh"]
          EOF
          
          docker build -t fedora32-tex .
          docker run --rm -v $(pwd):/app/output fedora32-tex

      - name: Prepare GitHub Pages
        run: |
          mkdir -p public/cv
          cp resume.pdf public/cv/
          
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8">
              <title>Resume - Ксения Шкулева</title>
              <meta http-equiv="refresh" content="0; url=cv/resume.pdf">
              <script>window.location.href="cv/resume.pdf";</script>
            </head>
            <body>
              <p>Redirecting to <a href="cv/resume.pdf">resume.pdf</a></p>
            </body>
          </html>' > public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          commit_message: "Auto-update: $(date -u +'%Y-%m-%d %H:%M')"
