name: Build Resume

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Debug files
        run: |
          echo "Repository contents:"
          ls -la
          ls -la CV/
          echo "build.sh exists: $(test -f build.sh && echo 'yes' || echo 'no')"
          echo "resume.tex exists: $(test -f CV/resume.tex && echo 'yes' || echo 'no')"
        
      - name: Build with Docker
        run: |
          docker build -t fedora32-tex .
          docker run --rm -v $(pwd):/app/output fedora32-tex

      - name: Verify PDF exists
        run: |
          if [ ! -f resume.pdf ]; then
            echo "PDF file not generated!"
            ls -la
            exit 1
          else
            echo "PDF generated successfully"
            ls -lh resume.pdf
          fi

      - name: Prepare GitHub Pages
        run: |
          mkdir -p public/cv
          cp resume.pdf public/cv/
          
          # Если в резюме есть изображения
          # cp -r CV/images public/cv/
          
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8">
              <title>Resume - Ксения Шкулева</title>
              <meta http-equiv="refresh" content="0; url=cv/resume.pdf">
              <script>window.location.href="cv/resume.pdf";</script>
            </head>
            <body>
              <p>Redirecting to <a href="cv/resume.pdf">resume.pdf</a></p>
            </body>
          </html>' > public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          commit_message: "Auto-update: $(date -u +'%Y-%m-%d %H:%M')"
