name: Build Resume

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Build with Fedora 32
        run: |
          # Запускаем контейнер Fedora 32
          docker run --rm -v $(pwd):/resume -w /resume fedora:32 /bin/bash -c "
            # Обновление системы
            dnf update -y -q
            
            # Установка TeX Live и зависимостей
            dnf install -y -q \
              texlive-scheme-full \
              texlive-collection-langcyrillic \
              texlive-luatex \
              dejavu-sans-fonts \
              wget \
              make
            
            # Переходим в директорию с резюме
            cd CV
            
            # Сборка PDF
            lualatex -interaction=nonstopmode resume.tex
            lualatex -interaction=nonstopmode resume.tex
          "

      - name: Prepare GitHub Pages
        run: |
          mkdir -p public/cv
          cp CV/resume.pdf public/cv/
          
          cat << 'EOF' > public/index.html
<!DOCTYPE html? <html> <head> <meta charset="UTF-8"> <title>Resume - Ксения Шкулева</title> <meta http-equiv="refresh" content="0; url=cv/resume.pdf"> <script>window.location.href="cv/resume.pdf";</script> </head> <body> <p>Redirecting to <a href="cv/resume.pdf">resume.pdf</a></p> </body </html>
EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          commit_message: "Auto-update: $(date -u +'%Y-%m-%d %H:%M')"
